### ISSUE TITLE
Wont Run

### ISSUE THREAD

**Issue by Rabb2269** [jpxue/Proxy_Toolkit_Scan-Scrape#1]
I cannot get it to run for the life of me.
I have Visual installed still will not run program.
How do i run it.

**Comment by jpxue** [comment]
What do you fully mean it won't run?
You need to be more descriptive than that.

Even the release files don't run: https://github.com/jpxue/Proxy_Scanner_Scraper_AIO/tree/master/release

If so, something must be blocking the program from running
